### ISSUE TITLE
add button to force schema data refresh

### ISSUE THREAD

**Issue by jweinstein** [wagonhq/feedback#20] opened 2016-02-17 20:05 UTC

**Comment by srobertson** [comment] 2016-02-17 20:06
For context:
In our org we create and modify a ton of tables a lot of them automatically. I use wagon to monitor production data changes. It's a pain to have to reconnect to see schema changes when someone else (robot deploy or human) makes a change to the schemas.

**Comment by jweinstein** [comment] 2016-02-17 20:08
Was talking to @benjamin-wagon, it should be straightforward.

**Comment by grano** [comment] 2016-03-09 19:26
Duplicate of https://github.com/wagonhq/feedback/issues/15

**Closed as completed by grano** 2016-03-09 19:26 UTC
Labels: duplicate, enhancement
